basePath: '{{.BasePath}}'
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: Golang Gin API Boilerplate
  license:
    name: MIT
    url: https://github.com/xxphenomxx/gogin/blob/master/LICENSE
  termsOfService: https://github.com/xxphenomxx/gogin
  title: Gogin API
  version: "1.0"
paths:
  /api/v1/tags/import:
    post:
      parameters:
      - description: Image File
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Import Image
  /user/email/{email}:
    get:
      description: Queries for a single User object by the email address provided
        otherwise will return an error
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Fetch a user record by email address
      tags:
      - user
  /user/get-or-create:
    post:
      description: Queries for a single User object by the email address provided,
        if it cannot locate one then it will create a new User record and return it
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      - description: Google ID
        in: path
        name: gID
        required: true
        type: string
      - description: Image URL
        in: path
        name: image
        required: true
        type: string
      - description: Users full name
        in: path
        name: full
        required: true
        type: string
      - description: First name
        in: path
        name: fn
        required: true
        type: string
      - description: Last name
        in: path
        name: ln
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Get or Create a User object - returns a User object and JWT token
      tags:
      - user
  /users/all:
    get:
      description: Returns an array of all User objects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Get users
      tags:
      - user
swagger: "2.0"
